### ISSUE TITLE
Some Suggestions

### ISSUE THREAD

**Issue by M-Razavi** [shuoros/all-about-spring#1]
To improve your repo, I suggest adding a CRUD (Create, Read, Update, Delete) scenario that includes all Controler, Service, Model, and persistence layers and corresponding best practices. 

Also, add Swagger for API documentation. (Better to have the latest version to support Open API)

**Comment by shuoros** [comment]
Hi Mahdi, Thanks for your suggestions. I'll definitely do what you said and I plan to do more on this repository. I would be glad to hear if you have other suggestions.

Feel free to any contribution on this project😃.
